#!/bin/sh
# Alacn, 2018-01-28

. /etc/bewan/scripts/globals
. /etc/bewan/lib/base

base_log "$SCRIPTD/ip-up-ppp run in background" debug
/etc/bewan/scripts/ip-up-ppp_ "${1:-}" "${2:-}" "${3:-}" "${4:-}" "${5:-}" "${6:-}" "${7:-}" &

