#!/bin/sh
# Alacn, 2018-01-28

. /etc/bewan/scripts/globals
. /etc/bewan/lib/base

base_log "$SCRIPTD/ppp-up6 run in background" debug
/etc/bewan/scripts/ppp-up6_ "${1:-}" "${2:-}" "${3:-}" "${4:-}" "${5:-}" &

