#!/bin/sh
# TR.111, WT.111 management
# The DHCP server (dnsmasq) has assigned a lease to a device in the LAN
# If the device is TR-111 (DHCP option 125 with IANA 3561)
# Create an entry in /var/bewan/tr111.d/device_param
# Create an entry in Services_TR111_Device

main_dhcp_tr111()
{
        
	if [ $ACTION != "add" ] || [ "${DNSMASQ_CPEWAN_OUI:-}" = '' ] || [ "${DNSMASQ_CPEWAN_SERIAL:-}" = '' ];  then
	        return
	fi

	local dir='/var/bewan/tr111.d'
	local device_file="$dir/device_param"
	mkdir -p $dir

	local type
        local DNSMASQ_DEVICE_111_TYPE=${DNSMASQ_DEVICE_111_TYPE:-1}
	if [ "${DNSMASQ_DEVICE_111_TYPE:-0}" = 1 ]; then
		type='TR111'
	else
		type='WT111'
	fi
	local oui="${DNSMASQ_CPEWAN_OUI:-}"
	if [ "$oui" = '' ]; then
		oui="${DNSMASQ_CPEWAN_OUI:-*}"
	fi
	local serial="${DNSMASQ_CPEWAN_SERIAL:-}"
	if [ "$serial" = '' ]; then
		serial="${DNSMASQ_CPEWAN_SERIAL:-*}"
	fi
	local class="${DNSMASQ_CPEWAN_CLASS:-}"
	if [ "$class" = '' ]; then
		class="${DNSMASQ_CPEWAN_CLASS:-*}"
	fi
	# Line to insert in device_param file
	local line="$MAC $IP $type $oui $serial $class"

	base_log "Update TR-111 device table for $line" debug

	# If MAC is already in device_file, replace it?
	local found="$(cat $device_file 2>/dev/null | grep $MAC)"
	if [ "$found" != '' ]; then
		# We found the device in the file, replace the line with the new one.
		sed -i "s/$MAC.*/$line/" $device_file
	else
		echo $line >>$device_file
	fi

	# Update the permanent table Services_TR111_Device
	base_call_scripts 'update_tr111_table'
}

#-------------------------------------------------------------------------------------------------
#function main
#-------------------------------------------------------------------------------------------------
main_dhcp_tr111
